# Generated by Django 6.0.6 on 2026-06-30 04:25

import cases.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('case_type', models.CharField(max_length=100)),
                ('judge_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('MENTION', 'Mention'), ('HEARING', 'Hearing'), ('RULING', 'Ruling'), ('CLOSED', 'Closed'), ('STAYED', 'Stayed')], db_index=True, default='FILED', max_length=20)),
                ('next_mention_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, db_index=True, null=True)),
                ('public_summary', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'Judiciary API'), ('CSV', 'CSV Import')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('station', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, choices=[('SUPREME', 'Supreme Court'), ('APPEAL', 'Court of Appeal'), ('HIGH', 'High Court'), ('EMPLOYMENT', 'Employment & Labour Relations Court'), ('ENVIRONMENT', 'Environment & Land Court'), ('MAGISTRATE', 'Magistrate Court'), ('KADHIS', 'Kadhis Court')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'courts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseAdvocate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advocate_name', models.CharField(db_index=True, max_length=255)),
                ('law_firm', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocates', to='cases.case')),
            ],
            options={
                'db_table': 'case_advocates',
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('MENTION', 'Mention'), ('HEARING', 'Hearing'), ('RULING', 'Ruling'), ('ADJOURNMENT', 'Adjournment'), ('UPDATE', 'Case Update'), ('FILING', 'Document Filing'), ('CLOSED', 'Case Closed')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_name', models.CharField(db_index=True, max_length=255)),
                ('party_role', models.CharField(choices=[('PLAINTIFF', 'Plaintiff'), ('DEFENDANT', 'Defendant'), ('ACCUSED', 'Accused'), ('APPLICANT', 'Applicant'), ('RESPONDENT', 'Respondent'), ('PETITIONER', 'Petitioner'), ('INTERESTED_PARTY', 'Interested Party')], max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case')),
            ],
            options={
                'db_table': 'case_parties',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.court'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=cases.models.Document._upload_path)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('PREMIUM', 'Premium Only')], default='PUBLIC', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracked_cases',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'case')},
            },
        ),
    ]
